### ISSUE TITLE
Example code fails to compile on posix

### ISSUE THREAD

**Issue by HeraldOD** [emoon/rust_minifb#394]
I've been working on a project using minifb and today it stopped compiling.
I've reproduced this issue using a fresh project with **only** the example code in the README.

System: Arch Linux x86_64, X11 (Xfce)

Here is the error:

```
   Compiling minifb v0.28.0
error[E0308]: arguments to this function are incorrect
   --> /home/herald/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/minifb-0.28.0/src/lib.rs:299:9
    |
299 |         imp::Window::new(name, width, height, opts).map(Window)
    |         ^^^^^^^^^^^^^^^^       -----  ------ expected `usize`, found `i32`
    |                                |
    |                                expected `usize`, found `i32`
    |
note: associated function defined here
   --> /home/herald/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/minifb-0.28.0/src/os/posix/mod.rs:43:12
    |
 43 |     pub fn new(name: &str, width: usize, height: usize, opts: WindowOptions) -> Result<Window> {
    |            ^^^             ------------  -------------
help: you can convert an `i32` to a `usize` and panic if the converted value doesn't fit
    |
299 |         imp::Window::new(name, width.try_into().unwrap(), height, opts).map(Window)
    |                                     ++++++++++++++++++++
help: you can convert an `i32` to a `usize` and panic if the converted value doesn't fit
    |
299 |         imp::Window::new(name, width, height.try_into().unwrap(), opts).map(Window)
    |                                             ++++++++++++++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `minifb` (lib) due to 1 previous error
```

The strange thing is the library compiles fine on its own if I clone it and run `cargo build`.
I don't understand why it's saying `width` and `height` are `i32` when the latest code on GitHub clearly says `usize`. Is there something I'm missing?

If I missed any more info that could be useful please let me know. I'm kind of new to Rust.
